### ISSUE TITLE
Is it possible to generate thumbnails from static images, such as NAIP tiles in Wisconsinview?

### ISSUE THREAD

**Issue by Wiscmapper** [WIStCart/GeoDataV2#159]

**Comment by ewlarson** [comment]
You'll want to follow this pattern:
https://github.com/geoblacklight/geoblacklight_sidecar_images#prioritize-solr-thumbnail-field-uris

**Comment by Wiscmapper** [comment]
Thumbnails stored by USGS appear to be in an S3 bucket, which are set to automatically download instead of viewing inline.  I have the "thumbnail_path_ss" field set, but the harvester isn't grabbing the images for processing. 

```"thumbnail_path_ss": "https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/PDF/WI/24000/WI_Zoar_502221_1973_24000_tn.jpg",```

Believe this has to do with content disposition/mime type set on the USGS side.  Need to research if there is a workaround.
