### ISSUE TITLE
Consider adding USGS 3DEP 1-meter DEMs

### ISSUE THREAD

**Issue by Wiscmapper** [WIStCart/GeoDataV2#161]

**Comment by Wiscmapper** [comment]
**Two options:**

1. Add individual tiles.  We already have a working script for this, and can add them anytime.

1. Develop a new script that assembles the response from Sciencebase into one or more tile indexes.

**Considerations:**

1. The dems are developed over time and made available, so how would we tile them if multiple vintages are available for a given location?  (can only have one download item per polygon in a tile index, and cannot have coincident polygons)

1. Need to investigate why there appears to be multiple versions of each tile for some locations.

**Comment by Wiscmapper** [comment]
Sent a message to Jim G. asking if he is familiar with the various USGS elevation products, and their value in comparison to original lidar held by WisconsinView.

**Comment by Wiscmapper** [comment]
From Jim G:

"So you are thinking about adding a link on Geodata to the individual USGS products, correct?   We try to have a copy of the USGS files on WisconsinView, so there would be some redundancy, but as long as you can make that clear that the underlying data is same, I don't think that's a problem to have two links.  We try to have the LAS uncompressed files, as opposed to USGS having the LAZ compressed versions.  LAZ is faster to download, but the LAS is more universally readable by GIS software.  Plus we can manipulate the header file easier with the LAS files, which seems to be necessary with WISCRS coordinates alot especially some of the earlier projects.

As for "original data" versus later "productized" that's a difficult concept to get across and we haven't made much attempt to explain it to users.  Case in point, Ashland 2014 lidar was flown by FEMA in 2014 and released only as LAS and breaklines in UTM.  Al Kirschbaum at NPS in Ashland reprocessed the ground points (there were many bad ground points), made DEMs and added some nifty forestry products.  Finally, Ashland Co paid Ayres to reprocess the FEMA originals, reclassify the ground, reproject to county coordinates, did contours and other enhancements.  All three collections are on WV, but a user wouldn't necessarily know which one to choose at this point.   USGS does not have a copy on their system.   NOAA does have e a copy on Digital Coast, transformed to a new geoid.   Yes there's original data, it wasn't very good, but others made it more usable.  So much for the idea of "authoritative data".  "

**Comment by jaimemartindale** [comment]
I'm thinking about this - but I wonder (since there is redundancy) if its better to focus our energy on WIView. I'm not afraid of doing some full-blown ISO metadata for these instead of just GBL generated by a script.  I'd like for Yu-Ning to dig into a project for the summer and WI View might be the best option to keep her tasked/busy.
